### ISSUE TITLE
Feature: User can view their favorite recipes

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of their favorited recipes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="297" alt="Screen Shot 2021-06-11 at 10 19 40 AM" src="https://user-images.githubusercontent.com/82540886/121725785-8b8f4d00-ca9e-11eb-832f-b987e661f8c3.png">
<img width="629" alt="Screen Shot 2021-06-11 at 10 19 57 AM" src="https://user-images.githubusercontent.com/82540886/121725805-94801e80-ca9e-11eb-8287-4ad822ebfb9f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the updatePageHeader function to update the page header when the user views their favorited recipes
- [x] Update the clickNavList function to check if the data-view attribute is for the favorites list
     - [x] When the user clicks on the favorites link, remove any current elements attached to the recipe-list view
     - [x] call the updatePageHeader function to change the page header to the favorite recipe view
     - [x] Repopulate the recipe-view page with recipes from the data.favorite array
- **Clean Up**
  - [x] Remove all console logs and comments
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
